Ros:
  node_name: "grace_api"
  queue_size: 100

  english_language_code: &id_lang_eng 'en-US' 
  cantonese_language_code: &id_lang_yue 'yue-Hant-HK' 

  primary_language_code: *id_lang_eng
  secondary_language_code: *id_lang_eng

  asr_words_topic: "/hr/perception/hear/words"
  asr_reconfig: "/hr/perception/speech_recognizer"
  asr_continuous: true
  asr_model: "phone_call"


  tts_data_service: "/hr/control/speech/data"
  tts_say_service: "/hr/control/speech/tts"
  tts_control_topic: "/hr/control/speech/tts_control"
  tts_event_topic: "/hr/control/speech/event"
  tts_stop_cmd: "shutup"
  tts_end_event: "stop"
  tts_pure_token: '|p|'

  arm_animation_topic: "/hr/animation/set_arm_animation"
  arm_animation_speed_reconfig: "/hr/animation/settings"

  expression_topic: "/hr/animation/set_expression"

  end_of_conv_topic: "/grace_proj/stop"
  grace_behavior_service: "/grace_proj/execute_behavior_command"


Behavior:
  arm_anim_min_dur: 0.5

  neutral_pose_info:
    name: "MAIN-1"
    dur: 4

  neutral_expression_info:
    name: "happy"
    dur: 3
    magnitude: 0

  bardging_in_monitor_rate: 30
  behav_exec_rate: 30

  succ_string: "completed"
  bardging_string: "interrupted"

Debug:
  bardging_in_switch_topic: "/grace_proj/stop_bardging_handling"

  Sample:
    txt: "Hello, this is a test script and I will just count. 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20."
    lang: *id_lang_eng

    expressions: ['happy','fear']
    exp_start: [0.1, 0.6]
    exp_end: [0.4, 0.9]
    exp_mag: [0.8, 0.8]

    gestures: ['MAIN-1','MAIN-2','MAIN-1']
    ges_start: [0.1, 0.4, 0.8]
    ges_end: [0.3, 0.5, 0.9] 
    ges_mag: [1, 1, 1] 
